### ISSUE TITLE
Tree expand misbehavior

### ISSUE THREAD

**Issue by xdghcnt** [SitePen/dstore#128] opened 2015-06-01 19:15 UTC
http://dgrid.io/js/dgrid/test/Tree_expand.html
1) Open Asia;
2) Open China;
3) Close Asia;
4) Open Asia;
5) Close China; ( http://puu.sh/i8INV/3ca44d5a40.png )
6) Open Russia and Mongolia ( http://puu.sh/i8IQd/3143655560.png )

**Comment by kfranqueiro** [comment] 2015-06-01 19:31
This seems like an issue with dgrid, not dstore.  It also sounds very similar to https://github.com/SitePen/dgrid/issues/1054, so I'm closing this as a duplicate of that (mentioning it here will reference this ticket there).

There is a workaround currently which involves disabling dgrid's tree transition logic (set `enableTreeTransitions: false`), since the issue has something to do with the calculation of height in that logic.

**Closed by kfranqueiro** 2015-06-01 19:31 UTC
