### ISSUE TITLE
Rest should append slash (/) before processing 'get', just like JsonRest

### ISSUE THREAD

**Issue by twelveeighty** [SitePen/dstore#112] opened 2015-03-21 20:45 UTC
While migrating code from JsonRest to dstore/Rest, I noticed that the Rest.get() method doesn't check for a trailing slash / at the end of the 'target' property before appending the 'id' to the request url. JsonRest checks for this.

**Comment by kriszyp** [comment] 2015-04-13 15:52
I think is a duplicate of #89 which was fixed with https://github.com/SitePen/dstore/commit/d44402563391fe19ca784b2d1b2a501cfc7bbb2e.

**Closed by kriszyp** 2015-04-13 15:52 UTC

**Comment by twelveeighty** [comment] 2015-05-01 20:16
@kriszyp, I'm not sure how you want to handle testing/verification of these issues, but I tested 267c620932d49ba5ff82ee2dfe287597066ef2f4 and this works fine now.  Are you planning a release anytime soon, btw?
